services:
  kratos:
    depends_on:
      - kratos-migrate
    image: oryd/kratos:v1.3.0
    command: serve -c /etc/config/kratos/config.yml --dev --watch-courier
    ports:
      - 4433:4433
    volumes:
      - type: bind
        source: ./kratos
        target: /etc/config/kratos
    networks:
      - internal

  kratos-migrate:
    depends_on:
      - db-kratos
    image: oryd/kratos:v1.3.0
    command: -c /etc/config/kratos/config.yml migrate sql -e --yes
    volumes:
      - type: bind
        source: ./kratos
        target: /etc/config/kratos
    networks:
      - internal
        
  db-kratos:
    image: postgres:16
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: kratos
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: kratos
    volumes:
      - type: volume
        source: db_kratos_data
        target: /var/lib/postgresql/data
        volume:
          nocopy: true
    networks:
      - internal

  mailslurper:
    image: oryd/mailslurper:latest-smtps
    ports:
      - 4436:4436
      - 4437:4437
      - 1025:1025
    networks:
      - internal

  app-sample:
    build:
      context: ./app/sample
      target: development
    command: > 
      /bin/bash -c '
        if [ "$$DEBUG" = "true" ]; then
          echo "debug mode"
          air -d -build.cmd "go build -gcflags \"all=-N -l\" -o tmp/main cmd/server/main.go && dlv exec --headless=true --listen=:2345 --continue --accept-multiclient ./tmp/main"
        else
          air
        fi
      '
    environment:
      TERM: xterm-256color
      DEBUG: "false"
    ports:
      - 3000:3000
      - 2345:2345
    working_dir: /root/app
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    volumes:
      - type: bind
        source: ./app/sample
        target: /root/app
      - type: volume
        source: api_airtmp
        target: /root/tmp
        volume:
          nocopy: true
      - type: bind
        source: ./.bashrc
        target: /root/.bashrc
      - ~/.aws:/root/.aws
    networks:
      - internal

volumes:
  db_kratos_data:
  api_airtmp:

networks:
  internal:
    name: kratos_sample-internal